export * from "./IndexPage.jsx";
export * from "./LoginPage.jsx";
export * from "./RegisterPage.jsx";
export * from "./CreatePost.jsx";
export * from "./PostPage.jsx";
export * from "./EditPost.jsx";
export * from "./Institutions.jsx";
export * from "./AboutUs.jsx"
export * from "./chat.jsx";